### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by CPFelix** [Bobo-y/triton_ensemble_model_demo#3]
When I try to load the post_detection model, I get the follow error:
"
I0815 07:41:03.988335 1 metrics.cc:184] found 1 GPUs supporting NVML metrics
I0815 07:41:03.994169 1 metrics.cc:193]   GPU 0: Tesla P4
I0815 07:41:04.224827 1 pinned_memory_manager.cc:195] Pinned memory pool is created at '0x7ff5a2000000' with size 268435456
I0815 07:41:04.226057 1 cuda_memory_manager.cc:98] CUDA memory pool is created on device 0 with size 67108864
E0815 07:41:21.783922 1 logging.cc:43] coreReadArchive.cpp (32) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
E0815 07:41:21.784074 1 logging.cc:43] INVALID_STATE: std::exception
E0815 07:41:21.784091 1 logging.cc:43] INVALID_CONFIG: Deserialize the cuda engine failed.
W0815 07:41:21.784113 1 autofill.cc:242] Autofiller failed to detect the platform for post_detection (verify contents of model directory or use --log-verbose=1 for more details)
W0815 07:41:21.784119 1 autofill.cc:265] Proceeding with simple config for now
I0815 07:41:21.792096 1 model_repository_manager.cc:714] loading: post_detection:1
Traceback (most recent call last):
  File "/opt/tritonserver/backends/python/startup.py", line 344, in <module>
    python_host = PythonHost(module_path=FLAGS.model_path)
  File "/opt/tritonserver/backends/python/startup.py", line 158, in __init__
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/foldergGpbts/1/model.py", line 30, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
"
Is it means I need install opencv in triton?

**Comment by Bobo-y** [comment]
@CPFelix yes, refer my dockerfile

**Comment by CPFelix** [comment]
@yl305237731 Can you provide the model file just for test? Thanks!

**Comment by yl305237731** [comment]
@CPFelix ok, this week

**Comment by CPFelix** [comment]
@yl305237731 sorry to interrupt again. 
Can you tell how to install cv2 in python backend of Triton. Thanks!
My Triton version is 21.03.

**Comment by Bobo-y** [comment]
@CPFelix in dockerfile. RUN pip install --upgrade pip && pip install -U opencv-python && apt-get upgrade  && apt update && apt install -y libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx \
    && pip install torch==1.5.0 && pip install torchvision==0.6.0 && pip install numpy.   [see](https://github.com/yl305237731/triton_ensemble_model_demo/blob/main/Dockerfile)
