### ISSUE TITLE
请问检测得矩阵的后处理得到框的操作哪里进行的？

### ISSUE THREAD

**Issue by pengyang1225** [Bobo-y/triton_ensemble_model_demo#4]
方便的话留下您的联系方法，请教问题

**Comment by Bobo-y** [comment]
@pengyang1225 只是把nms 那一套搬到triton里，python 或者 pytorch 的nms 复制过去就行

**Comment by pengyang1225** [comment]
我不知道怎么将一些后处理加进去，您这边可以提供一下案例吗

**Comment by pengyang1225** [comment]
我看懂您的级联方后处理加到管道的方式，您这边可以指导一下吗

**Comment by Bobo-y** [comment]
@pengyang1225 我手里目前没有案例了，换工作了，没用triton了
