### ISSUE TITLE
How can i find classification model

### ISSUE THREAD

**Issue by lihuahua123** [Bobo-y/triton_ensemble_model_demo#5]
Thanks for your code. The classification model is efficient-net.keras, input-size: 260, return 3 class, background, wear vest, no wear vest.  How can i find the model ?

**Comment by Bobo-y** [comment]
@lihuahua123 hi，i not upload that model,  just a demo

**Comment by Bobo-y** [comment]
this code update two year ago, 
I don't know if it's still working
